export const SET_LOGIN_VALUE = 'SET_LOGIN_VALUE';
export const SET_PASSWORD_VALUE = 'SET_PASSWORD_VALUE';
export const SET_LOGIN_ERROR_MESSAGE = 'SET_LOGIN_ERROR_MESSAGE';
export const SET_PASSWORD_ERROR_MESSAGE ='SET_PASSWORD_ERROR_MESSAGE';
export const SET_CLEAR_LOGIN_ERROR_MESSAGE = 'SET_CLEAR_LOGIN_ERROR_MESSAGE';
export const SET_CLEAR_PASSWORD_ERROR_MESSAGE = 'SET_CLEAR_PASSWORD_ERROR_MESSAGE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_CHECKED = 'SET_CHECKED';
