export const SET_PEOPLE = 'SET_PEOPLE';
export const SET_LOADING = 'SET_LOADING';
export const SET_PLANET_LOADING = 'SET_PLANET_LOADING';
export const SET_CURRENT_CREATURE = 'SET_CURRENT_CREATURE';
export const SET_CREATURE_PLANET = 'SET_CREATURE_PLANET';
export const CLEAR_CREATURE_DETAILS = 'CLEAR_CREATURE_DETAILS';
export const SET_PEOPLE_COUNT = 'SET_PEOPLE_COUNT';
