export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
export const SET_LOADING = 'SET_LOADING';
export const SET_POKEMON_LOADING = 'SET_POKEMON_LOADING';
export const CLEAR_CURRENT_POKEMON = 'CLEAR_CURRENT_POKEMON';
